# Generated by Django 6.0.2 on 2026-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=80)),
                ('Duree', models.IntegerField()),
                ('Creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormationsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=80)),
                ('Categorie', models.CharField()),
                ('Duree', models.FloatField()),
                ('Nombre_Diplome', models.CharField()),
                ('Nombre_Heure', models.FloatField()),
                ('Date_Creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
