# Generated by Django 6.0.2 on 2026-05-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveAjout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField()),
                ('Prenom', models.CharField()),
                ('Sexe', models.CharField()),
                ('Dossier', models.BooleanField()),
                ('Image', models.ImageField(default='default.jpg', upload_to='static/Images/DataImage')),
                ('Parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTools.formationsmodels')),
            ],
        ),
    ]
